spring.application.name=demo2
##paymentGateway.type=paytm
#paymentGateway.retry-count=5

payment-properties.type=paytm
payment-properties.retry-count=5
payment-properties.enabled=true
payment-properties.timeout=3000
